CREATE TABLE IF NOT EXISTS musics (
    music_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    music_name VARCHAR(255) NOT NULL,
    composer VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);